# Generated by Django 5.2.6 on 2025-09-18 23:59

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoguetePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Torne-se um Foguete Kaizen', max_length=200, verbose_name='Título do Hero')),
                ('hero_subtitle', models.TextField(default='Faça parte de uma equipe que acredita na melhoria contínua e na excelência operacional.', verbose_name='Subtítulo do Hero')),
                ('culture_title', models.CharField(default='Nossa Cultura Kaizen', max_length=200, verbose_name='Título da Cultura')),
                ('culture_content', wagtail.fields.RichTextField(default='A filosofia Kaizen é o coração da nossa empresa. Acreditamos na melhoria contínua e no poder das pequenas mudanças que geram grandes transformações.', verbose_name='Conteúdo sobre Cultura')),
                ('five_s_title', models.CharField(default='Os 5S da Kaizen', max_length=200, verbose_name='Título dos 5S')),
                ('five_s_content', wagtail.fields.RichTextField(default='Nossos valores são baseados nos 5S da filosofia Kaizen: Seiri (Organização), Seiton (Ordenação), Seiso (Limpeza), Seiketsu (Padronização) e Shitsuke (Disciplina).', verbose_name='Conteúdo dos 5S')),
                ('benefits_title', models.CharField(default='Por que ser um Foguete Kaizen?', max_length=200, verbose_name='Título dos Benefícios')),
                ('benefits_content', wagtail.fields.RichTextField(default='Junte-se a uma equipe que valoriza a inovação, o crescimento pessoal e profissional, e a busca constante pela excelência.', verbose_name='Conteúdo dos Benefícios')),
                ('cta_title', models.CharField(default='Pronto para Decolar?', max_length=200, verbose_name='Título do CTA')),
                ('cta_subtitle', models.TextField(default='Envie sua candidatura e faça parte da nossa missão de transformar negócios através do marketing digital.', verbose_name='Subtítulo do CTA')),
            ],
            options={
                'verbose_name': 'Página Torne-se um Foguete',
                'verbose_name_plural': 'Páginas Torne-se um Foguete',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('address', models.TextField(verbose_name='Endereço Completo')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('current_position', models.CharField(max_length=200, verbose_name='Cargo Atual')),
                ('current_company', models.CharField(max_length=200, verbose_name='Empresa Atual')),
                ('experience_years', models.IntegerField(verbose_name='Anos de Experiência')),
                ('education_level', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('tecnico', 'Ensino Técnico'), ('superior_incompleto', 'Superior Incompleto'), ('superior_completo', 'Superior Completo'), ('pos_graduacao', 'Pós-graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=50, verbose_name='Nível de Escolaridade')),
                ('course_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do Curso')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Instituição')),
                ('desired_area', models.CharField(choices=[('marketing_digital', 'Marketing Digital'), ('vendas', 'Vendas'), ('desenvolvimento', 'Desenvolvimento'), ('design', 'Design'), ('atendimento', 'Atendimento'), ('rh', 'Recursos Humanos'), ('financeiro', 'Financeiro'), ('operacional', 'Operacional'), ('gestao', 'Gestão'), ('outro', 'Outro')], max_length=100, verbose_name='Área de Interesse')),
                ('availability', models.CharField(choices=[('imediata', 'Imediata'), ('1_mes', '1 mês'), ('2_meses', '2 meses'), ('3_meses', '3 meses'), ('mais_3_meses', 'Mais de 3 meses')], max_length=50, verbose_name='Disponibilidade')),
                ('technical_skills', models.TextField(verbose_name='Habilidades Técnicas')),
                ('languages', models.TextField(verbose_name='Idiomas')),
                ('certifications', models.TextField(blank=True, verbose_name='Certificações')),
                ('crm_experience', models.BooleanField(default=False, verbose_name='Experiência com CRM')),
                ('social_media_experience', models.BooleanField(default=False, verbose_name='Experiência com Redes Sociais')),
                ('google_ads_experience', models.BooleanField(default=False, verbose_name='Experiência com Google Ads')),
                ('facebook_ads_experience', models.BooleanField(default=False, verbose_name='Experiência com Facebook Ads')),
                ('analytics_experience', models.BooleanField(default=False, verbose_name='Experiência com Analytics')),
                ('seo_experience', models.BooleanField(default=False, verbose_name='Experiência com SEO')),
                ('content_creation_experience', models.BooleanField(default=False, verbose_name='Experiência com Criação de Conteúdo')),
                ('motivation', models.TextField(verbose_name='Motivação para Trabalhar na Kaizen')),
                ('salary_expectation', models.CharField(max_length=100, verbose_name='Pretensão Salarial')),
                ('career_goals', models.TextField(verbose_name='Objetivos de Carreira')),
                ('linkedin_profile', models.URLField(blank=True, verbose_name='Perfil LinkedIn')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfólio/Website')),
                ('referral_source', models.CharField(choices=[('site', 'Site da Empresa'), ('linkedin', 'LinkedIn'), ('indicação', 'Indicação'), ('google', 'Google'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('outro', 'Outro')], max_length=100, verbose_name='Como Conheceu a Vaga')),
                ('resume_file', models.FileField(blank=True, upload_to='recruitment/resumes/', verbose_name='Currículo')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Carta de Apresentação')),
                ('status', models.CharField(choices=[('nova', 'Nova'), ('em_analise', 'Em Análise'), ('entrevista', 'Entrevista'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='nova', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Formulário de Candidatura', max_length=200, verbose_name='Título do Hero')),
                ('hero_subtitle', models.TextField(default='Preencha o formulário abaixo para se candidatar a uma vaga na Kaizen.', verbose_name='Subtítulo do Hero')),
                ('form_instructions', wagtail.fields.RichTextField(default='Por favor, preencha todos os campos obrigatórios com informações verdadeiras e atualizadas.', verbose_name='Instruções do Formulário')),
                ('privacy_policy', wagtail.fields.RichTextField(default='Seus dados serão utilizados exclusivamente para o processo seletivo e não serão compartilhados com terceiros.', verbose_name='Política de Privacidade')),
            ],
            options={
                'verbose_name': 'Página de Recrutamento',
                'verbose_name_plural': 'Páginas de Recrutamento',
            },
            bases=('wagtailcore.page',),
        ),
    ]
