# Generated by Django 5.2.6 on 2025-09-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foguetepage',
            options={'verbose_name': 'Página Quero Ser um Foguete', 'verbose_name_plural': 'Páginas Quero Ser um Foguete'},
        ),
        migrations.AlterField(
            model_name='foguetepage',
            name='hero_title',
            field=models.CharField(default='Quero Ser um Foguete Kaizen', max_length=200, verbose_name='Título do Hero'),
        ),
    ]
