# Generated by Django 5.2.6 on 2025-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_update_foguete_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='instagram_profile',
            field=models.CharField(blank=True, max_length=100, verbose_name='Perfil Instagram'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='work_modality_preference',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='remoto', max_length=20, verbose_name='Modalidade de Preferência'),
        ),
    ]
