# Generated by Django 5.2.6 on 2025-09-19 00:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaProgramaticaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', wagtail.fields.RichTextField(blank=True, help_text='Título principal da página')),
                ('hero_subtitle', wagtail.fields.RichTextField(blank=True, help_text='Subtítulo da página')),
                ('hero_cta_text', models.CharField(default='Solicitar Consultoria Gratuita', help_text='Texto do botão CTA principal', max_length=100)),
                ('tech_title', models.CharField(default='Tecnologia Avançada', help_text='Título da seção de tecnologia', max_length=200)),
                ('tech_description', wagtail.fields.RichTextField(blank=True, help_text='Descrição da tecnologia utilizada')),
                ('channels_title', models.CharField(default='Canais de Mídia', help_text='Título da seção de canais', max_length=200)),
                ('channels_subtitle', models.CharField(default='Cobertura completa em todos os pontos de contato com seu público', help_text='Subtítulo da seção de canais', max_length=300)),
                ('process_title', models.CharField(default='Como Trabalhamos', help_text='Título da seção de processo', max_length=200)),
                ('process_subtitle', models.CharField(default='Processo estruturado para máxima eficiência e resultados', help_text='Subtítulo da seção de processo', max_length=300)),
                ('benefits_title', models.CharField(default='Por que Escolher Nossa Plataforma?', help_text='Título da seção de benefícios', max_length=200)),
                ('final_cta_title', wagtail.fields.RichTextField(blank=True, help_text='Título do CTA final')),
                ('final_cta_subtitle', wagtail.fields.RichTextField(blank=True, help_text='Subtítulo do CTA final')),
                ('final_cta_button_text', models.CharField(default='Solicitar Consultoria Gratuita', help_text='Texto do botão CTA final', max_length=100)),
                ('final_cta_secondary_text', models.CharField(default='Ver Cases de Sucesso', help_text='Texto do botão secundário', max_length=100)),
                ('final_cta_secondary_url', models.URLField(blank=True, help_text='URL do botão secundário')),
                ('custom_seo_title', models.CharField(blank=True, help_text='Título SEO customizado (se diferente do título da página)', max_length=200)),
                ('custom_seo_description', models.TextField(blank=True, help_text='Descrição SEO customizada', max_length=300)),
            ],
            options={
                'verbose_name': 'Página de Mídia Programática',
                'verbose_name_plural': 'Páginas de Mídia Programática',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='servicesindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ServiceFeature',
        ),
        migrations.DeleteModel(
            name='ServicePage',
        ),
        migrations.DeleteModel(
            name='ServicesIndexPage',
        ),
    ]
