# Generated by Django 5.2.6 on 2025-09-18 19:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato: (11) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('monthly_revenue', models.CharField(blank=True, choices=[('ate_10k', 'Até R$ 10.000'), ('10k_50k', 'R$ 10.000 - R$ 50.000'), ('50k_100k', 'R$ 50.000 - R$ 100.000'), ('100k_500k', 'R$ 100.000 - R$ 500.000'), ('500k_1m', 'R$ 500.000 - R$ 1.000.000'), ('acima_1m', 'Acima de R$ 1.000.000')], max_length=50, verbose_name='Faturamento Mensal')),
                ('business_area', models.CharField(blank=True, choices=[('ecommerce', 'E-commerce'), ('saas', 'SaaS/Software'), ('servicos', 'Serviços'), ('varejo', 'Varejo'), ('industria', 'Indústria'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('imobiliaria', 'Imobiliária'), ('automotivo', 'Automotivo'), ('outros', 'Outros')], max_length=100, verbose_name='Área do Negócio')),
                ('main_challenge', models.TextField(blank=True, help_text='Descreva o principal desafio de marketing que podemos ajudar', verbose_name='Principal Desafio do Negócio')),
                ('website_social', models.CharField(blank=True, help_text='Website ou rede social da empresa', max_length=200, verbose_name='Site ou Rede Social')),
                ('status', models.CharField(choices=[('step1', 'Passo 1 - Dados Básicos'), ('step2', 'Passo 2 - Informações do Negócio'), ('step3', 'Passo 3 - Calendly'), ('completed', 'Completo')], default='step1', max_length=20, verbose_name='Status')),
                ('calendly_event_id', models.CharField(blank=True, max_length=100, verbose_name='ID do Evento Calendly')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Agendamento')),
                ('confirmation_email_sent', models.BooleanField(default=False, verbose_name='Email de Confirmação Enviado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
