# Generated by Django 5.2.6 on 2025-09-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre objetivos e expectativas', verbose_name='Informações Adicionais'),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_activity',
            field=models.CharField(blank=True, choices=[('marketing-digital', 'Marketing Digital'), ('vendas', 'Vendas'), ('gestao-empresarial', 'Gestão Empresarial'), ('tecnologia', 'Tecnologia'), ('consultoria', 'Consultoria'), ('outro', 'Outro')], max_length=100, verbose_name='Área de Atuação Atual'),
        ),
        migrations.AddField(
            model_name='lead',
            name='experience_years',
            field=models.CharField(blank=True, choices=[('0-1', '0 a 1 ano'), ('2-5', '2 a 5 anos'), ('6-10', '6 a 10 anos'), ('10+', 'Mais de 10 anos')], max_length=20, verbose_name='Anos de Experiência'),
        ),
        migrations.AddField(
            model_name='lead',
            name='franchise_timeline',
            field=models.CharField(blank=True, choices=[('imediato', 'Imediato (até 30 dias)'), ('3-meses', '3 meses'), ('6-meses', '6 meses'), ('1-ano', '1 ano'), ('mais-1-ano', 'Mais de 1 ano')], max_length=50, verbose_name='Prazo para Início da Franquia'),
        ),
        migrations.AddField(
            model_name='lead',
            name='franchise_type',
            field=models.CharField(blank=True, choices=[('consultoria', 'Franquia de Consultoria'), ('agencia', 'Franquia de Agência'), ('ambas', 'Ambas as opções')], max_length=50, verbose_name='Tipo de Franquia de Interesse'),
        ),
        migrations.AddField(
            model_name='lead',
            name='investment_range',
            field=models.CharField(blank=True, choices=[('ate-50k', 'Até R$ 50.000'), ('50k-100k', 'R$ 50.000 a R$ 100.000'), ('100k-200k', 'R$ 100.000 a R$ 200.000'), ('200k-500k', 'R$ 200.000 a R$ 500.000'), ('acima-500k', 'Acima de R$ 500.000')], max_length=50, verbose_name='Faixa de Investimento'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('business', 'Lead de Negócio'), ('franchise', 'Lead de Franquia')], default='business', max_length=20, verbose_name='Tipo de Lead'),
        ),
    ]
