# Generated by Django 5.2.6 on 2025-09-18 23:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_additional_info_lead_current_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('utm_term', models.CharField(blank=True, max_length=100, verbose_name='UTM Term')),
                ('utm_content', models.CharField(blank=True, max_length=100, verbose_name='UTM Content')),
                ('referrer', models.URLField(blank=True, verbose_name='Referrer')),
                ('landing_page', models.URLField(blank=True, verbose_name='Página de Entrada')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='Session ID')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Dispositivo')),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='Navegador')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='Sistema Operacional')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'UTM Parameters',
                'verbose_name_plural': 'UTM Parameters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Touchpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Visualização de Página'), ('modal_open', 'Abertura da Modal'), ('step1_start', 'Início do Step 1'), ('step1_complete', 'Conclusão do Step 1'), ('step2_start', 'Início do Step 2'), ('step2_complete', 'Conclusão do Step 2'), ('step3_start', 'Início do Step 3 (Calendly)'), ('step3_complete', 'Conclusão do Step 3'), ('step4_complete', 'Conclusão do Step 4'), ('form_submit', 'Envio do Formulário'), ('calendly_scheduled', 'Agendamento no Calendly'), ('email_sent', 'Email Enviado'), ('conversion', 'Conversão Completa')], max_length=50, verbose_name='Tipo de Evento')),
                ('event_data', models.JSONField(blank=True, default=dict, verbose_name='Dados do Evento')),
                ('step_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do Step')),
                ('page_url', models.URLField(blank=True, verbose_name='URL da Página')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Touchpoint',
                'verbose_name_plural': 'Touchpoints',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.utmparameters', verbose_name='Parâmetros UTM'),
        ),
    ]
