# Generated by Django 5.2.6 on 2025-09-18 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogpage', verbose_name='Post em destaque'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem para redes sociais'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Post em destaque'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='reading_time',
            field=models.PositiveIntegerField(default=5, help_text='Tempo estimado de leitura em minutos'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem para redes sociais'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de publicação'),
        ),
    ]
