# Generated by Django 5.2.6 on 2025-09-18 17:15

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_featured_post_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, through='blog.BlogPageTag', to='taggit.tag', verbose_name='Tags'),
        ),
    ]
