# Generated by Django 5.2.6 on 2025-09-18 20:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_tags'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='blogpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='blogpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogtagindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='featured_post',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='social_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='reading_time',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_image',
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(verbose_name='Post date'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='EvergreenPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(help_text='Título principal da página (H1)', max_length=255, verbose_name='Título Principal')),
                ('hero_subtitle', wagtail.fields.RichTextField(blank=True, help_text='Subtítulo ou descrição principal', verbose_name='Subtítulo')),
                ('hero_background_color', models.CharField(default='#000000', help_text='Cor hexadecimal (ex: #000000)', max_length=7, verbose_name='Cor de Fundo do Hero')),
                ('meta_description', models.TextField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160, verbose_name='Meta Description')),
                ('focus_keyword', models.CharField(blank=True, help_text='Palavra-chave principal para SEO', max_length=100, verbose_name='Palavra-chave Principal')),
                ('cta_title', models.CharField(blank=True, help_text='Título da seção de call-to-action', max_length=255, verbose_name='Título do CTA')),
                ('cta_text', wagtail.fields.RichTextField(blank=True, help_text='Texto da seção de call-to-action', verbose_name='Texto do CTA')),
                ('cta_button_text', models.CharField(default='Saiba Mais', max_length=100, verbose_name='Texto do Botão CTA')),
                ('cta_button_url', models.URLField(blank=True, verbose_name='URL do Botão CTA')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 5), ('raw_html', 6), ('embed', 7), ('cta_section', 12), ('features_list', 14), ('pricing_table', 19), ('testimonials', 22), ('faq_section', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'blocks/paragraph.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'template': 'blocks/image.html'}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('author', 4)]], {'icon': 'openquote', 'template': 'blocks/quote.html'}), 6: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code', 'template': 'blocks/raw_html.html'}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'template': 'blocks/embed.html'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.URLBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'default': '#ea0029'}), 12: ('wagtail.blocks.StructBlock', [[('title', 8), ('text', 9), ('button_text', 8), ('button_url', 10), ('background_color', 11)]], {'icon': 'link', 'template': 'blocks/cta_section.html'}), 13: ('wagtail.blocks.StructBlock', [[('title', 8), ('description', 3), ('icon', 4)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'icon': 'list-ul', 'template': 'blocks/features_list.html'}), 15: ('wagtail.blocks.ListBlock', (3,), {}), 16: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('name', 8), ('price', 8), ('period', 8), ('features', 15), ('button_text', 8), ('button_url', 10), ('highlighted', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 8), ('plans', 18)]], {'icon': 'table', 'template': 'blocks/pricing_table.html'}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 21: ('wagtail.blocks.StructBlock', [[('name', 8), ('company', 8), ('text', 3), ('image', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'icon': 'quote', 'template': 'blocks/testimonials.html'}), 23: ('wagtail.blocks.StructBlock', [[('question', 8), ('answer', 9)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'icon': 'help', 'template': 'blocks/faq_section.html'})}, verbose_name='Conteúdo da Página')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem Hero')),
            ],
            options={
                'verbose_name': 'Página Evergreen',
                'verbose_name_plural': 'Páginas Evergreen',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogPageTag',
        ),
        migrations.DeleteModel(
            name='BlogTagIndexPage',
        ),
    ]
