# Generated by Django 5.2.6 on 2025-09-17 13:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem Sobre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Texto Sobre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título Sobre'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Texto Contato'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título Contato'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem Hero'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Bem-vindo à Agência Kaizen', max_length=255, verbose_name='Título Principal'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Texto Portfolio'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título Portfolio'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Texto Serviços'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título Serviços'),
        ),
    ]
