# Generated by Django 5.2.6 on 2025-09-18 17:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_about_image_homepage_about_text_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Aqui, só decola quem está pronto para voar mais alto.', max_length=255, verbose_name='Título Principal')),
                ('hero_subtitle', wagtail.fields.RichTextField(default='Desde 2015, a Kaizen não segue o mercado. Ela acelera, transforma e redefine as regras do jogo. Mais do que uma agência, somos uma aceleradora de vendas que entrega crescimento real. Se o objetivo é escalar, somos o combustível.', verbose_name='Subtítulo Principal')),
                ('results_title', models.CharField(default='Resultados que não cabem em promessas', max_length=255, verbose_name='Título da Seção de Resultados')),
                ('results_subtitle', models.TextField(default='Nós entregamos performance de verdade. Confira alguns dos nossos resultados:', verbose_name='Subtítulo da Seção de Resultados')),
                ('history_title', models.CharField(default='Conheça nossa história', max_length=255, verbose_name='Título da Seção de História')),
                ('history_text', wagtail.fields.RichTextField(blank=True, verbose_name='Texto da História')),
                ('team_title', models.CharField(default='Apenas os melhores jogam no nosso time.', max_length=255, verbose_name='Título da Seção do Time')),
                ('team_text', wagtail.fields.RichTextField(blank=True, verbose_name='Texto da Seção do Time')),
                ('meta_description', models.TextField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=255)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Fundo do Hero')),
            ],
            options={
                'verbose_name': 'Página Quem Somos',
                'verbose_name_plural': 'Páginas Quem Somos',
            },
            bases=('wagtailcore.page',),
        ),
    ]
