# Generated by Django 5.2.6 on 2025-09-18 17:52

import home.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='contact_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contact_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='portfolio_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='portfolio_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('results_section', 3), ('solutions_section', 5), ('competences_section', 7), ('cta_section', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtítulo', 'max_length': 500}), 2: ('wagtail.blocks.ListBlock', (home.models.ResultCardBlock,), {'label': 'Cards de Resultados'}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('results', 2)]], {'label': 'Seção de Resultados'}), 4: ('wagtail.blocks.ListBlock', (home.models.SolutionCardBlock,), {'label': 'Cards de Soluções'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('solutions', 4)]], {'label': 'Seção de Soluções'}), 6: ('wagtail.blocks.ListBlock', (home.models.CompetenceCardBlock,), {'label': 'Cards de Competências'}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('competences', 6)]], {'label': 'Seção de Competências'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 255}), 9: ('wagtail.blocks.CharBlock', (), {'default': '0800-550-8000', 'label': 'Telefone', 'max_length': 50}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'Olá! Vim pelo site da Agência Kaizen e gostaria de saber mais sobre os serviços.', 'label': 'Texto do WhatsApp', 'max_length': 200}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('subtitle', 1), ('phone', 9), ('whatsapp_text', 10)]], {'label': 'Seção de Call-to-Action'})}, verbose_name='Seções da Página'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, default='<p>Com processos, metodologia e execução prática, ajudamos empresas a crescer de forma sustentável e escalável.</p>', verbose_name='Texto Sobre'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, default='Somos uma aceleradora de vendas.', max_length=255, verbose_name='Título Sobre'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=wagtail.fields.RichTextField(blank=True, default='<p>Desde 2014, ajudamos empresas a crescer com estratégias afiadas, dados precisos e um time de elite. Se sua meta é escalar, nós temos o combustível.</p>', verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Aceleramos negócios e lançamos foguetes', max_length=255, verbose_name='Título Principal'),
        ),
    ]
