# Generated by Django 5.2.6 on 2025-09-19 10:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_contact_text_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OndeEstamosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Presença forte.\nCrescimento sem limites.', max_length=255, verbose_name='Título Principal (Hero)')),
                ('hero_subtitle', wagtail.fields.RichTextField(default='Com escritórios estrategicamente posicionados nas principais capitais do Brasil, estamos próximos aos nossos clientes. Onde quer que você esteja, a Kaizen está pronta para acelerar seu negócio.', verbose_name='Subtítulo do Hero')),
                ('offices', wagtail.fields.StreamField([('office', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Cidade/Unidade', 'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Endereço (linhas com <br>)'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Telefone (com DDD)', 'max_length': 50}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'URL do Google Maps'}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('address', 1), ('phone', 2), ('map_url', 3)]], {})}, verbose_name='Escritórios')),
                ('cta_phone', models.CharField(default='0800-550-8000', max_length=50, verbose_name='Telefone CTA')),
                ('expansion_title', models.CharField(default='Acelere negócios.\nExpanda com a Kaizen.', max_length=255, verbose_name='Título da Seção de Expansão')),
                ('expansion_text_1', wagtail.fields.RichTextField(default='A Kaizen é mais que uma agência. É uma aceleradora de negócios com presença nacional e metodologia comprovada. Nossos escritórios não são apenas endereços, são centros de inovação onde estratégias se transformam em resultados.', verbose_name='Texto 1 da Seção de Expansão')),
                ('expansion_text_2', wagtail.fields.RichTextField(default='Seja qual for sua cidade, nossa expertise é sua grande aliada para escalar vendas, otimizar processos e transformar seu negócio em uma máquina de crescimento.', verbose_name='Texto 2 da Seção de Expansão')),
                ('expansion_cta_text', models.CharField(default='QUERO MAIS SOBRE A EXPANSÃO KAIZEN', max_length=80, verbose_name='Texto do Botão (Expansão)')),
                ('expansion_cta_url', models.CharField(default='/contato/', max_length=255, verbose_name='URL do Botão (Expansão)')),
                ('franchise_title', models.CharField(default='Por que se tornar um franqueado Kaizen?', max_length=255, verbose_name='Título Benefícios Franquia')),
                ('franchise_benefits', wagtail.fields.StreamField([('benefit', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 120}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Descrição'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})}, verbose_name='Benefícios')),
                ('franchises', wagtail.fields.StreamField([('franchise', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 150}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Descrição'}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'QUERO MAIS INFORMAÇÕES', 'label': 'Texto do Botão', 'max_length': 80}), 3: ('wagtail.blocks.CharBlock', (), {'default': '/contato/', 'label': 'URL do Botão', 'max_length': 255}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('cta_text', 2), ('cta_url', 3)]], {})}, verbose_name='Opções de Franquia')),
                ('access_title', models.CharField(default='Acesso exclusivo e\ninvestimento sólido', max_length=255, verbose_name='Título Seção Acesso')),
                ('access_text', wagtail.fields.RichTextField(blank=True, verbose_name='Texto Seção Acesso')),
                ('access_cta_text', models.CharField(default='QUERO SABER MAIS', max_length=80, verbose_name='Texto do Botão (Acesso)')),
                ('access_cta_url', models.CharField(default='/contato/', max_length=255, verbose_name='URL do Botão (Acesso)')),
                ('testimonials', wagtail.fields.StreamField([('testimonial', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Citação'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Autor', 'max_length': 120}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Cargo/Unidade', 'max_length': 120, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('quote', 0), ('author', 1), ('role', 2)]], {})}, verbose_name='Depoimentos')),
                ('final_cta_title', models.CharField(default='Expanda. Cresça. Conquiste. Entre para o time Kaizen.', max_length=255, verbose_name='Título CTA Final')),
                ('final_cta_text', wagtail.fields.RichTextField(blank=True, default='Pronto para fazer parte de um dos grupos que mais cresce no Brasil? Preencha o formulário e descubra como se tornar um franqueado Kaizen.', verbose_name='Texto CTA Final')),
                ('show_interest_form', models.BooleanField(default=True, verbose_name='Exibir formulário de interesse')),
            ],
            options={
                'verbose_name': 'Página Onde Estamos',
                'verbose_name_plural': 'Páginas Onde Estamos',
            },
            bases=('wagtailcore.page',),
        ),
    ]
