# Generated by Django 5.2.6 on 2025-09-19 13:05

import home.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_ondeestamospage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('results_section', 3), ('solutions_section', 5), ('competences_section', 7), ('clients_carousel', 9), ('cta_section', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtítulo', 'max_length': 500}), 2: ('wagtail.blocks.ListBlock', (home.models.ResultCardBlock,), {'label': 'Cards de Resultados'}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('results', 2)]], {'label': 'Seção de Resultados'}), 4: ('wagtail.blocks.ListBlock', (home.models.SolutionCardBlock,), {'label': 'Cards de Soluções', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('solutions', 4)]], {'label': 'Seção de Soluções'}), 6: ('wagtail.blocks.ListBlock', (home.models.CompetenceCardBlock,), {'label': 'Cards de Competências'}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('competences', 6)]], {'label': 'Seção de Competências'}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Marcas que confiam', 'label': 'Título', 'max_length': 255}), 9: ('wagtail.blocks.StructBlock', [[('title', 8)]], {'label': 'Carrossel de Clientes'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 255}), 11: ('wagtail.blocks.CharBlock', (), {'default': '0800-550-8000', 'label': 'Telefone', 'max_length': 50}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Olá! Vim pelo site da Agência Kaizen e gostaria de saber mais sobre os serviços.', 'label': 'Texto do WhatsApp', 'max_length': 200}), 13: ('wagtail.blocks.StructBlock', [[('title', 10), ('subtitle', 1), ('phone', 11), ('whatsapp_text', 12)]], {'label': 'Seção de Call-to-Action'})}, verbose_name='Seções da Página'),
        ),
    ]
