# Generated by Django 5.2.6 on 2025-09-19 13:21

import home.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='ceo',
            field=wagtail.fields.StreamField([('ceo', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'CEO', 'label': 'Nome', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Chief Executive Officer', 'label': 'Cargo', 'max_length': 120}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Foto', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Bio curta', 'required': False}), 4: ('wagtail.blocks.ListBlock', (home.models.CEOSocialLinkBlock,), {'label': 'Links sociais', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('photo', 2), ('bio', 3), ('social', 4)]], {})}, verbose_name='Seção CEO'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='final_cta_button_text',
            field=models.CharField(default='FALAR COM ESPECIALISTA', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='final_cta_button_url',
            field=models.CharField(default='/contato/', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='final_cta_subtitle',
            field=models.CharField(blank=True, default='Vamos acelerar seu crescimento com método e performance.', max_length=500),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='final_cta_title',
            field=models.CharField(blank=True, default='Pronto para decolar?', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='metrics_block',
            field=wagtail.fields.StreamField([('metrics', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Resultados que não cabem em promessas', 'label': 'Título', 'max_length': 255}), 1: ('wagtail.blocks.ListBlock', (home.models.MetricBlock,), {'label': 'Métricas'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('metrics', 1)]], {})}, verbose_name='Seção de Métricas'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(blank=True, default='Nossa missão e propósito', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='units_block',
            field=wagtail.fields.StreamField([('units', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Unidades de negócio', 'label': 'Título', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtítulo', 'max_length': 500, 'required': False}), 2: ('wagtail.blocks.ListBlock', (home.models.UnitCardBlock,), {'label': 'Cards'}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('units', 2)]], {})}, verbose_name='Unidades de Negócio'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_block',
            field=wagtail.fields.StreamField([('values', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Nossos valores', 'label': 'Título', 'max_length': 255}), 1: ('wagtail.blocks.ListBlock', (home.models.ValueCardBlock,), {'label': 'Valores'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('values', 1)]], {})}, verbose_name='Valores'),
        ),
    ]
