# Generated by Django 5.2.6 on 2025-09-18 16:19

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Texto introdutório da página')),
                ('hero_title', models.CharField(default='Mais que uma agência, um ecossistema de crescimento.', max_length=200, verbose_name='Título principal')),
                ('hero_subtitle', wagtail.fields.RichTextField(blank=True, default='<p>A Kaizen é mais que uma agência. Somos um grupo de empresas que acelera negócios em diferentes áreas.</p>', verbose_name='Subtítulo principal')),
                ('meta_description', models.TextField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#D62042', help_text='Cor em hexadecimal (ex: #D62042)', max_length=7, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Categoria de Empresa',
                'verbose_name_plural': 'Categorias de Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('tagline', models.CharField(max_length=200, verbose_name='Slogan/Tagline')),
                ('description', wagtail.fields.RichTextField(verbose_name='Descrição')),
                ('website_url', models.URLField(blank=True, verbose_name='Site da empresa')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contato')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('meta_description', models.TextField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160)),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Data de fundação')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem em destaque')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companycategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('additional_content', wagtail.fields.RichTextField(blank=True, verbose_name='Conteúdo adicional')),
                ('cta_title', models.CharField(default='Interessado em saber mais?', max_length=100, verbose_name='Título do CTA')),
                ('cta_text', models.TextField(default='Entre em contato e descubra como podemos ajudar seu negócio.', verbose_name='Texto do CTA')),
                ('cta_button_text', models.CharField(default='Fale Conosco', max_length=50, verbose_name='Texto do botão')),
                ('cta_button_url', models.URLField(blank=True, help_text='Deixe em branco para usar a página de contato', verbose_name='URL do botão')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CompanyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, help_text='Ex: fas fa-chart-line', max_length=50, verbose_name='Ícone Font Awesome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('company', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='companies.company')),
            ],
            options={
                'verbose_name': 'Funcionalidade',
                'verbose_name_plural': 'Funcionalidades',
                'ordering': ['order'],
            },
        ),
    ]
