# Generated by Django 5.2.6 on 2025-09-18 19:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companydetailpage_company'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('address', models.TextField(verbose_name='Endereço completo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_main_office', models.BooleanField(default=False, verbose_name='Escritório principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'ordering': ['order', 'city'],
            },
        ),
        migrations.CreateModel(
            name='LocationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Presença forte. Crescimento sem limites.', max_length=200, verbose_name='Título principal')),
                ('hero_subtitle', wagtail.fields.RichTextField(default='<p>Estamos nas principais regiões do Brasil levando estratégias de alto performance para empresas que querem acelerar. Desde que você esteja, a Kaizen está pronta para impulsionar seu negócio.</p>', verbose_name='Subtítulo principal')),
                ('locations_title', models.CharField(default='Se sua meta é crescer, nós estamos por perto.', max_length=200, verbose_name='Título das localizações')),
                ('locations_subtitle', models.CharField(default='Nossas experiências', max_length=200, verbose_name='Subtítulo das localizações')),
                ('franchise_title', models.CharField(default='Acelere negócios. Expanda com a Kaizen.', max_length=200, verbose_name='Título da franquia')),
                ('franchise_subtitle', models.CharField(default='SEJA DONO DA SUA PRÓPRIA BASE DE LANÇAMENTO', max_length=200, verbose_name='Subtítulo da franquia')),
                ('franchise_text', wagtail.fields.RichTextField(default='<p>A Kaizen não é apenas uma agência, é um modelo de negócio que funciona. Com mais de 15 anos de experiência e resultados comprovados, oferecemos a oportunidade de se tornar um franqueado e replicar nosso sucesso em sua região.</p><p>Nossa metodologia exclusiva, suporte completo e marca reconhecida no mercado garantem que você tenha todas as ferramentas necessárias para acelerar negócios e construir uma base sólida de crescimento.</p>', verbose_name='Texto da franquia')),
                ('franchise_button_text', models.CharField(default='Quero saber mais sobre a franquia Kaizen', max_length=100, verbose_name='Texto do botão da franquia')),
                ('benefits_title', models.CharField(default='Por que se tornar um franqueado Kaizen?', max_length=200, verbose_name='Título dos benefícios')),
                ('models_title', models.CharField(default='Se você quer empreender no mercado de marketing e vendas com um modelo de negócios sólido, esta é a sua chance.', max_length=200, verbose_name='Título dos modelos')),
                ('models_subtitle', models.CharField(default='Expansão estratégica com alto performance: conheça nossos modelos de franquia', max_length=200, verbose_name='Subtítulo dos modelos')),
                ('investment_title', models.CharField(default='Acesso exclusivo e investimento sólido', max_length=200, verbose_name='Título do investimento')),
                ('investment_text', wagtail.fields.RichTextField(default='<p>Ser um franqueado Kaizen significa ter acesso exclusivo a nossa metodologia comprovada, treinamento especializado e suporte contínuo. Investimos em cada unidade para garantir que você tenha todas as ferramentas necessárias para o sucesso.</p><p>Nossa equipe de especialistas está sempre disponível para apoiar seu crescimento e garantir que você alcance os melhores resultados possíveis.</p>', verbose_name='Texto do investimento')),
                ('testimonials_title', models.CharField(default='Veja o que dizem nossos franqueados', max_length=200, verbose_name='Título dos depoimentos')),
                ('contact_title', models.CharField(default='Expanda. Cresça. Conquiste. Entre para o time Kaizen.', max_length=200, verbose_name='Título do contato')),
                ('contact_subtitle', models.CharField(default='Preencha o formulário e fale com nosso time de expansão.', max_length=200, verbose_name='Subtítulo do contato')),
                ('meta_description', models.TextField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
