# Generated by Django 5.2.6 on 2025-09-18 20:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_location_locationpage'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Potencialize suas vendas com automação + CRM', max_length=200, verbose_name='Título principal')),
                ('hero_subtitle', models.CharField(default='Menos esforço. Mais conversões. Gestão otimizada.', max_length=200, verbose_name='Subtítulo principal')),
                ('hero_description', wagtail.fields.RichTextField(default='<p>Integre automação de vendas e CRM em uma única solução. Transforme leads em clientes de forma automática e eficiente, com controle total sobre seu funil de vendas.</p>', verbose_name='Descrição do hero')),
                ('problem_title', models.CharField(default='Você sabe quanto tempo e dinheiro está perdendo?', max_length=200, verbose_name='Título dos problemas')),
                ('problem_text', wagtail.fields.RichTextField(default='<p>Se a sua empresa enfrenta esses desafios, está na hora de transformar seu processo comercial.</p><p>Com o Fluxo, você automatiza suas vendas e estrutura um CRM eficiente para acelerar seus resultados.</p>', verbose_name='Texto dos problemas')),
                ('solution_title', models.CharField(default='Fluxo: Automação inteligente para sua empresa crescer', max_length=200, verbose_name='Título da solução')),
                ('solution_description', wagtail.fields.RichTextField(default='<p>O Fluxo da Kaizen é uma solução completa de automação comercial + CRM, criada para empresas que querem crescer sem perder controle sobre seus processos.</p>', verbose_name='Descrição da solução')),
                ('solution_conclusion', wagtail.fields.RichTextField(default='<p>Esqueça planilhas e processos manuais. Com o Fluxo, sua empresa opera no piloto automático e foca no que realmente importa: vender mais!</p>', verbose_name='Conclusão da solução')),
                ('benefits_title', models.CharField(default='Empresas que implementam automação de vendas e CRM têm:', max_length=200, verbose_name='Título dos benefícios')),
                ('benefits_conclusion', wagtail.fields.RichTextField(default='<p>Chegou a hora de estruturar sua operação comercial e escalar suas vendas.</p>', verbose_name='Conclusão dos benefícios')),
                ('how_it_works_title', models.CharField(default='Como Funciona?', max_length=200, verbose_name='Título como funciona')),
                ('how_it_works_conclusion', wagtail.fields.RichTextField(default='<p>Chegou a hora de estruturar sua operação comercial e escalar suas vendas.</p>', verbose_name='Conclusão como funciona')),
                ('faq_title', models.CharField(default='Perguntas frequentes', max_length=200, verbose_name='Título FAQ')),
                ('kaizen_title', wagtail.fields.RichTextField(default='<p>A Kaizen é referência em estratégias de automação de marketing e vendas, ajudando empresas a estruturar processos eficientes e previsíveis.</p>', verbose_name='Título Kaizen')),
                ('kaizen_conclusion', wagtail.fields.RichTextField(default='<p>Vamos transformar sua operação comercial? Entre em contato agora!</p>', verbose_name='Conclusão Kaizen')),
                ('final_cta_title', models.CharField(default='Não fique para trás! Empresas que automatizam suas vendas crescem mais rápido e com previsibilidade.', max_length=200, verbose_name='Título CTA final')),
                ('final_cta_subtitle', models.CharField(default='Preencha o formulário e descubra como transformar sua operação comercial!', max_length=200, verbose_name='Subtítulo CTA final')),
                ('meta_description', models.TextField(default='Fluxo: Solução completa de automação comercial + CRM da Kaizen. Automatize suas vendas, qualifique leads e acelere conversões.', help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem do hero')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
