# Generated by Django 5.2.6 on 2025-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_seed_initial_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='BR', max_length=2, verbose_name='País (ISO)'),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='maps_url',
            field=models.URLField(blank=True, verbose_name='URL do Google Maps'),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Agência Kaizen', max_length=120, verbose_name='Nome da Unidade'),
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Horário de funcionamento (ex: Mo-Fr 08:00-18:00)'),
        ),
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='Google Place ID'),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default='SP', max_length=2, verbose_name='UF'),
        ),
    ]
