# Generated by Django 5.2.6 on 2025-09-18 23:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=20, unique=True, verbose_name='Número da Aplicação')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviada'), ('under_review', 'Em Análise'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('scheduled', 'Agendada'), ('completed', 'Concluída')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato: (11) 99999-9999', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('marital_status', models.CharField(choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widowed', 'Viúvo(a)')], max_length=20, verbose_name='Estado Civil')),
                ('nationality', models.CharField(default='Brasileira', max_length=100, verbose_name='Nacionalidade')),
                ('address', models.CharField(max_length=300, verbose_name='Endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zipcode', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Formato: 00000-000', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('profession', models.CharField(max_length=100, verbose_name='Profissão')),
                ('current_company', models.CharField(blank=True, max_length=200, verbose_name='Empresa Atual')),
                ('current_position', models.CharField(blank=True, max_length=100, verbose_name='Cargo Atual')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Anos de Experiência')),
                ('education_level', models.CharField(choices=[('elementary', 'Ensino Fundamental'), ('high_school', 'Ensino Médio'), ('technical', 'Técnico'), ('college', 'Superior'), ('postgraduate', 'Pós-graduação'), ('master', 'Mestrado'), ('phd', 'Doutorado')], max_length=20, verbose_name='Nível de Escolaridade')),
                ('management_experience', models.CharField(choices=[('none', 'Nenhuma'), ('low', 'Pouca (1-2 anos)'), ('medium', 'Média (3-5 anos)'), ('high', 'Alta (6-10 anos)'), ('expert', 'Expert (10+ anos)')], max_length=20, verbose_name='Experiência em Gestão')),
                ('sales_experience', models.CharField(choices=[('none', 'Nenhuma'), ('low', 'Pouca (1-2 anos)'), ('medium', 'Média (3-5 anos)'), ('high', 'Alta (6-10 anos)'), ('expert', 'Expert (10+ anos)')], max_length=20, verbose_name='Experiência em Vendas')),
                ('marketing_experience', models.CharField(choices=[('none', 'Nenhuma'), ('low', 'Pouca (1-2 anos)'), ('medium', 'Média (3-5 anos)'), ('high', 'Alta (6-10 anos)'), ('expert', 'Expert (10+ anos)')], max_length=20, verbose_name='Experiência em Marketing')),
                ('investment_capacity', models.CharField(choices=[('low', 'Até R$ 50.000'), ('medium', 'R$ 50.000 - R$ 150.000'), ('high', 'R$ 150.000 - R$ 300.000'), ('very_high', 'Acima de R$ 300.000')], max_length=20, verbose_name='Capacidade de Investimento')),
                ('preferred_city', models.CharField(max_length=100, verbose_name='Cidade de Interesse')),
                ('preferred_state', models.CharField(max_length=2, verbose_name='Estado de Interesse')),
                ('preferred_region', models.CharField(blank=True, max_length=100, verbose_name='Região de Interesse')),
                ('expected_start_date', models.DateField(verbose_name='Data Esperada para Início')),
                ('team_size', models.CharField(choices=[('solo', 'Só eu'), ('small', '2-5 pessoas'), ('medium', '6-15 pessoas'), ('large', '16-50 pessoas'), ('enterprise', '50+ pessoas')], max_length=20, verbose_name='Tamanho da Equipe Pretendida')),
                ('target_market', models.CharField(blank=True, max_length=200, verbose_name='Mercado-Alvo de Interesse')),
                ('business_goals', models.TextField(verbose_name='Objetivos de Negócio')),
                ('why_franchise', models.TextField(verbose_name='Por que quer ser franqueado?')),
                ('expected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Receita Esperada')),
                ('available_time', models.CharField(choices=[('part_time', 'Meio período'), ('full_time', 'Tempo integral'), ('weekends', 'Fins de semana'), ('flexible', 'Flexível')], max_length=20, verbose_name='Tempo Disponível')),
                ('risk_tolerance', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], max_length=20, verbose_name='Tolerância ao Risco')),
                ('references', models.TextField(blank=True, verbose_name='Referências')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='franchise/documents/', verbose_name='Currículo')),
                ('business_plan', models.FileField(blank=True, null=True, upload_to='franchise/documents/', verbose_name='Plano de Negócios')),
                ('financial_statement', models.FileField(blank=True, null=True, upload_to='franchise/documents/', verbose_name='Demonstrativo Financeiro')),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='franchise/documents/', verbose_name='Documento de Identidade')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='franchise/documents/', verbose_name='Comprovante de Endereço')),
                ('income_proof', models.FileField(blank=True, null=True, upload_to='franchise/documents/', verbose_name='Comprovante de Renda')),
                ('meeting_scheduled', models.BooleanField(default=False, verbose_name='Reunião Agendada')),
                ('meeting_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Reunião')),
                ('meeting_notes', models.TextField(blank=True, verbose_name='Observações da Reunião')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('utm_term', models.CharField(blank=True, max_length=100, verbose_name='UTM Term')),
                ('utm_content', models.CharField(blank=True, max_length=100, verbose_name='UTM Content')),
                ('referrer', models.URLField(blank=True, verbose_name='Referrer')),
                ('landing_page', models.URLField(blank=True, verbose_name='Página de Entrada')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='Session ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações Internas')),
            ],
            options={
                'verbose_name': 'Aplicação de Franqueado',
                'verbose_name_plural': 'Aplicações de Franqueados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('curriculum', 'Currículo'), ('business_plan', 'Plano de Negócios'), ('financial_statement', 'Demonstrativo Financeiro'), ('identity_document', 'Documento de Identidade'), ('address_proof', 'Comprovante de Endereço'), ('income_proof', 'Comprovante de Renda'), ('other', 'Outro')], max_length=30, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='franchise/documents/', verbose_name='Arquivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamanho do Arquivo')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enviado em')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Observações de Verificação')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='franchise.franchiseapplication', verbose_name='Aplicação')),
            ],
            options={
                'verbose_name': 'Documento de Franqueado',
                'verbose_name_plural': 'Documentos de Franqueados',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseTouchpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Visualização de Página'), ('modal_open', 'Abertura da Modal'), ('step1_start', 'Início do Step 1'), ('step1_complete', 'Conclusão do Step 1'), ('step2_start', 'Início do Step 2'), ('step2_complete', 'Conclusão do Step 2'), ('step3_start', 'Início do Step 3'), ('step3_complete', 'Conclusão do Step 3'), ('step4_start', 'Início do Step 4'), ('step4_complete', 'Conclusão do Step 4'), ('step5_start', 'Início do Step 5'), ('step5_complete', 'Conclusão do Step 5'), ('step6_complete', 'Conclusão do Step 6'), ('form_submit', 'Envio do Formulário'), ('document_upload', 'Upload de Documento'), ('meeting_scheduled', 'Reunião Agendada'), ('application_submitted', 'Aplicação Enviada'), ('conversion', 'Conversão Completa')], max_length=50, verbose_name='Tipo de Evento')),
                ('event_data', models.JSONField(blank=True, default=dict, verbose_name='Dados do Evento')),
                ('step_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do Step')),
                ('page_url', models.URLField(blank=True, verbose_name='URL da Página')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='franchise.franchiseapplication', verbose_name='Aplicação')),
            ],
            options={
                'verbose_name': 'Touchpoint de Franqueado',
                'verbose_name_plural': 'Touchpoints de Franqueados',
                'ordering': ['-timestamp'],
            },
        ),
    ]
