# Generated by Django 5.2.6 on 2025-09-18 23:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introdução da página')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2), ('quote', 5), ('raw_html', 6)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('quote', 3), ('attribution', 4)]], {}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Raw HTML'})})),
                ('meta_description', models.TextField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=255)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Tempo estimado de leitura em minutos')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem para redes sociais')),
            ],
            options={
                'verbose_name': 'Página Padrão',
                'verbose_name_plural': 'Páginas Padrão',
            },
            bases=('wagtailcore.page',),
        ),
    ]
