# Generated by Django 5.2.6 on 2025-09-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='highlight_subtitle',
            field=models.CharField(default='Estamos prontos para atender você!', max_length=200, verbose_name='Subtítulo de Destaque'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='highlight_title',
            field=models.CharField(default='Fale Conosco', max_length=100, verbose_name='Título de Destaque'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_0800',
            field=models.CharField(default='0800-550-8000', max_length=20, verbose_name='0800'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='whatsapp',
            field=models.CharField(default='0800-550-8000', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
