# Generated by Django 5.2.6 on 2025-09-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpage_highlight_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='whatsapp',
            field=models.CharField(default='11999999999', help_text='Número do WhatsApp sem formatação (ex: 11999999999)', max_length=20, verbose_name='WhatsApp (apenas números)'),
        ),
    ]
