# Generated by Django 5.2.6 on 2025-09-18 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactpage_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do template')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto do email')),
                ('html_content', models.TextField(verbose_name='Conteúdo HTML')),
                ('text_content', models.TextField(blank=True, verbose_name='Conteúdo texto')),
                ('category', models.CharField(choices=[('contact_confirmation', 'Confirmação de Contato'), ('contact_notification', 'Notificação de Contato'), ('newsletter', 'Newsletter'), ('welcome', 'Boas-vindas')], max_length=30, verbose_name='Categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Template de Email',
                'verbose_name_plural': 'Templates de Email',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Empresa')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de envio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do remetente')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('page_url', models.URLField(blank=True, verbose_name='URL da página')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Data do envio do email')),
                ('email_error', models.TextField(blank=True, verbose_name='Erro no envio')),
                ('subject_category', models.CharField(choices=[('orcamento', 'Solicitar Orçamento'), ('duvida', 'Dúvida sobre Serviços'), ('suporte', 'Suporte Técnico'), ('parceria', 'Parceria'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria do assunto')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_andamento', 'Em Andamento'), ('respondido', 'Respondido'), ('finalizado', 'Finalizado')], default='novo', max_length=20, verbose_name='Status')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atribuído para')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-created_at'],
            },
        ),
    ]
