# Generated by Django 5.2.6 on 2025-09-19 00:58

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_emailtemplate_contactmessage'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Conecte-se com a Kaizen', max_length=255, verbose_name='Título Principal')),
                ('hero_subtitle', wagtail.fields.RichTextField(default='Siga nossa jornada nas redes sociais e fique por dentro de tudo que acontece na nossa aceleradora de vendas.', verbose_name='Subtítulo Principal')),
                ('instagram_title', models.CharField(default='Nosso Instagram', max_length=255, verbose_name='Título da Seção Instagram')),
                ('instagram_subtitle', models.TextField(default='Acompanhe nosso dia a dia, cases de sucesso e dicas de marketing digital.', verbose_name='Subtítulo da Seção Instagram')),
                ('instagram_username', models.CharField(default='digitakaizen', max_length=100, verbose_name='Username do Instagram')),
                ('instagram_url', models.URLField(default='https://www.instagram.com/digitakaizen/', verbose_name='URL do Instagram')),
                ('linkedin_title', models.CharField(default='Nosso LinkedIn', max_length=255, verbose_name='Título da Seção LinkedIn')),
                ('linkedin_subtitle', models.TextField(default='Conteúdo profissional, insights de mercado e networking de qualidade.', verbose_name='Subtítulo da Seção LinkedIn')),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com/company/kaizenmarketingdigital/', verbose_name='URL do LinkedIn')),
                ('cta_title', models.CharField(default='Vamos Conectar?', max_length=255, verbose_name='Título do CTA')),
                ('cta_subtitle', wagtail.fields.RichTextField(default='Escolha sua rede social preferida e vamos conversar sobre como acelerar seu negócio!', verbose_name='Subtítulo do CTA')),
                ('meta_description', models.TextField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=255)),
            ],
            options={
                'verbose_name': 'Página Conecte-se',
                'verbose_name_plural': 'Páginas Conecte-se',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='blog_sidebar', max_length=100)),
                ('page_url', models.URLField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.RemoveField(
            model_name='contactformfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='contactformpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='email_error',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='email_sent_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject_category',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='page_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ContactFormField',
        ),
        migrations.DeleteModel(
            name='ContactFormPage',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
