# Generated by Django 5.2.6 on 2025-09-19 01:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do curso', max_length=200)),
                ('description', wagtail.fields.RichTextField(help_text='Descrição do curso')),
                ('duration', models.CharField(help_text='Duração do curso', max_length=100)),
                ('level', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], help_text='Nível do curso', max_length=50)),
                ('thumbnail', models.ImageField(help_text='Thumbnail do curso', upload_to='cursos/')),
                ('is_free', models.BooleanField(default=True, help_text='Curso gratuito')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço do curso', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do expert', max_length=200)),
                ('title', models.CharField(help_text='Título/cargo do expert', max_length=300)),
                ('bio', wagtail.fields.RichTextField(help_text='Biografia do expert')),
                ('photo', models.ImageField(help_text='Foto do expert', upload_to='experts/')),
                ('specialties', models.CharField(help_text='Especialidades (separadas por vírgula)', max_length=500)),
                ('social_linkedin', models.URLField(blank=True, help_text='LinkedIn do expert')),
                ('social_instagram', models.URLField(blank=True, help_text='Instagram do expert')),
                ('social_twitter', models.URLField(blank=True, help_text='Twitter do expert')),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Experts',
            },
        ),
        migrations.CreateModel(
            name='UniversidadeKaizenPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', wagtail.fields.RichTextField(default="<span class='text-pink'>Universidade Kaizen</span>", help_text='Título principal da seção Hero')),
                ('hero_subtitle', wagtail.fields.RichTextField(default='Evolução contínua para performance máxima', help_text='Subtítulo da seção Hero')),
                ('hero_description', wagtail.fields.RichTextField(default='O conhecimento certo pode transformar qualquer negócio. Na Universidade Kaizen, você tem acesso ao que há de mais avançado em marketing digital, vendas e estratégias de crescimento.', help_text='Descrição da seção Hero')),
                ('hero_cta_text', models.CharField(default='QUERO PARTICIPAR', help_text='Texto do botão CTA na seção Hero', max_length=100)),
                ('hero_image', models.ImageField(help_text='Imagem principal da seção Hero', upload_to='universidade/')),
                ('about_title', models.CharField(default='Por que a Universidade Kaizen?', help_text='Título da seção sobre', max_length=200)),
                ('about_description', wagtail.fields.RichTextField(default='Aqui, você encontra cursos gratuitos e trilhas completas ministradas pelos maiores especialistas do mercado. Conteúdo prático, atualizado e focado em resultados reais.', help_text='Descrição da seção sobre')),
                ('advantages_title', models.CharField(default='O que você vai encontrar', help_text='Título da seção de vantagens', max_length=200)),
                ('experts_title', models.CharField(default='Conheça nossos especialistas', help_text='Título da seção de experts', max_length=200)),
                ('experts_subtitle', models.CharField(default='Aprenda com os melhores profissionais do mercado', help_text='Subtítulo da seção de experts', max_length=300)),
                ('cursos_title', models.CharField(default='Cursos Disponíveis', help_text='Título da seção de cursos', max_length=200)),
                ('cursos_subtitle', models.CharField(default='Conteúdo prático e atualizado para acelerar seu crescimento', help_text='Subtítulo da seção de cursos', max_length=300)),
                ('final_cta_title', wagtail.fields.RichTextField(default="Pronto para <span class='text-pink'>Evoluir</span> seu Conhecimento?", help_text='Título do CTA final')),
                ('final_cta_subtitle', wagtail.fields.RichTextField(default='Junte-se a milhares de profissionais que já transformaram seus negócios com a Universidade Kaizen.', help_text='Subtítulo do CTA final')),
                ('final_cta_button_text', models.CharField(default='COMEÇAR AGORA', help_text='Texto do botão principal do CTA final', max_length=100)),
                ('custom_seo_title', models.CharField(blank=True, help_text='Título SEO personalizado', max_length=200)),
                ('custom_seo_description', models.TextField(blank=True, help_text='Descrição SEO personalizada', max_length=300)),
            ],
            options={
                'verbose_name': 'Página da Universidade Kaizen',
                'verbose_name_plural': 'Páginas da Universidade Kaizen',
            },
            bases=('wagtailcore.page',),
        ),
    ]
