# Generated by Django 5.2.6 on 2025-09-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidadekaizenpage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Imagem principal da seção Hero', null=True, upload_to='universidade/'),
        ),
    ]
