# Generated by Django 5.2.6 on 2025-09-18 17:30

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do ícone')),
                ('icon_class', models.CharField(max_length=100, verbose_name='Classe do ícone (FontAwesome)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Ícone de Serviço',
                'verbose_name_plural': 'Ícones de Serviços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('custom_icon_class', models.CharField(blank=True, help_text='Se preenchido, será usado em vez do ícone selecionado', max_length=100, verbose_name='Classe de ícone personalizada')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('meta_description', models.TextField(blank=True, help_text='Descrição para SEO', max_length=160)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solutions.serviceicon', verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SolutionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Seção')),
                ('subtitle', models.TextField(verbose_name='Subtítulo/Descrição')),
                ('background_color', models.CharField(choices=[('bg-dark', 'Escuro'), ('bg-black', 'Preto'), ('bg-primary', 'Primário')], default='bg-dark', max_length=20, verbose_name='Cor de Fundo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cta_text', models.CharField(default='Converse com um especialista', max_length=100, verbose_name='Texto do CTA')),
                ('cta_url', models.URLField(default='/contato/', verbose_name='URL do CTA')),
                ('services', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Selecione os serviços desta seção', to='solutions.service', verbose_name='Serviços')),
            ],
            options={
                'verbose_name': 'Seção de Soluções',
                'verbose_name_plural': 'Seções de Soluções',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SolutionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Estratégias de impacto para resultados reais', max_length=200, verbose_name='Título Principal')),
                ('hero_subtitle', wagtail.fields.RichTextField(blank=True, help_text='Texto introdutório da página', verbose_name='Subtítulo Principal')),
                ('final_cta_title', models.CharField(default='Está pronto para transformar suas oportunidades em vendas reais?', max_length=200, verbose_name='Título do CTA Final')),
                ('final_cta_subtitle', models.TextField(default='Nossa equipe de especialistas está pronta para analisar seu negócio e desenvolver a estratégia perfeita para acelerar seu crescimento.', verbose_name='Subtítulo do CTA Final')),
                ('final_cta_button_text', models.CharField(default='Converse com um especialista', max_length=100, verbose_name='Texto do Botão CTA Final')),
                ('meta_description', models.TextField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=255)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Fundo do Hero')),
            ],
            options={
                'verbose_name': 'Página de Soluções',
                'verbose_name_plural': 'Páginas de Soluções',
            },
            bases=('wagtailcore.page',),
        ),
    ]
