# Generated by Django 5.2.6 on 2025-09-18 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do evento para o GTM (ex: contact_form_submit)', max_length=100, verbose_name='Nome do Evento')),
                ('display_name', models.CharField(help_text='Nome amigável do evento', max_length=200, verbose_name='Nome para Exibição')),
                ('description', models.TextField(blank=True, help_text='Descrição do que o evento rastreia', verbose_name='Descrição')),
                ('category', models.CharField(default='engagement', help_text='Categoria do evento (ex: engagement, conversion, navigation)', max_length=50, verbose_name='Categoria')),
                ('is_conversion', models.BooleanField(default=False, help_text='Marcar se este evento representa uma conversão', verbose_name='É Conversão')),
                ('is_active', models.BooleanField(default=True, help_text='Ativar/desativar este evento', verbose_name='Ativo')),
                ('custom_parameters', models.JSONField(blank=True, default=dict, help_text='Parâmetros adicionais em formato JSON', verbose_name='Parâmetros Personalizados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento Personalizado',
                'verbose_name_plural': 'Eventos Personalizados',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtm_container_id', models.CharField(default='GTM-5JCWMWQ', help_text='ID do container do Google Tag Manager (ex: GTM-5JCWMWQ)', max_length=20, verbose_name='GTM Container ID')),
                ('gtm_enabled', models.BooleanField(default=True, help_text='Ativar/desativar o Google Tag Manager', verbose_name='GTM Ativo')),
                ('ga4_measurement_id', models.CharField(blank=True, help_text='ID de medição do Google Analytics 4 (ex: G-XXXXXXXXXX)', max_length=20, verbose_name='GA4 Measurement ID')),
                ('ga4_enabled', models.BooleanField(default=False, help_text='Ativar/desativar o Google Analytics 4', verbose_name='GA4 Ativo')),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='ID do Facebook Pixel', max_length=20, verbose_name='Facebook Pixel ID')),
                ('facebook_pixel_enabled', models.BooleanField(default=False, verbose_name='Facebook Pixel Ativo')),
                ('linkedin_partner_id', models.CharField(blank=True, help_text='ID do LinkedIn Insight Tag', max_length=20, verbose_name='LinkedIn Partner ID')),
                ('linkedin_enabled', models.BooleanField(default=False, verbose_name='LinkedIn Tracking Ativo')),
                ('track_form_submissions', models.BooleanField(default=True, help_text='Enviar evento quando formulários forem enviados', verbose_name='Rastrear Envio de Formulários')),
                ('track_phone_clicks', models.BooleanField(default=True, help_text='Enviar evento quando números de telefone forem clicados', verbose_name='Rastrear Cliques em Telefone')),
                ('track_whatsapp_clicks', models.BooleanField(default=True, help_text='Enviar evento quando links do WhatsApp forem clicados', verbose_name='Rastrear Cliques no WhatsApp')),
                ('track_email_clicks', models.BooleanField(default=True, help_text='Enviar evento quando links de email forem clicados', verbose_name='Rastrear Cliques em Email')),
                ('track_external_links', models.BooleanField(default=True, help_text='Enviar evento quando links externos forem clicados', verbose_name='Rastrear Links Externos')),
                ('track_scroll_depth', models.BooleanField(default=True, help_text='Enviar eventos de scroll (25%, 50%, 75%, 100%)', verbose_name='Rastrear Profundidade de Scroll')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configurações de Analytics',
                'verbose_name_plural': 'Configurações de Analytics',
            },
        ),
    ]
