# Generated by Django 5.2.6 on 2025-09-18 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_overlay_opacity', models.DecimalField(decimal_places=2, default=0.4, help_text='Opacidade da sobreposição escura sobre a imagem de fundo (0.0 = transparente, 1.0 = opaco)', max_digits=3)),
                ('background_position', models.CharField(choices=[('center', 'Centro'), ('top', 'Topo'), ('bottom', 'Inferior'), ('left', 'Esquerda'), ('right', 'Direita'), ('top left', 'Topo Esquerda'), ('top right', 'Topo Direita'), ('bottom left', 'Inferior Esquerda'), ('bottom right', 'Inferior Direita')], default='center', help_text='Posicionamento da imagem de fundo', max_length=50)),
                ('background_size', models.CharField(choices=[('cover', 'Cobrir (Cover)'), ('contain', 'Conter (Contain)'), ('auto', 'Automático'), ('100% 100%', 'Esticar')], default='cover', help_text='Como a imagem deve ser redimensionada', max_length=50)),
                ('background_repeat', models.CharField(choices=[('no-repeat', 'Não repetir'), ('repeat', 'Repetir'), ('repeat-x', 'Repetir horizontalmente'), ('repeat-y', 'Repetir verticalmente')], default='no-repeat', help_text='Como a imagem deve ser repetida', max_length=50)),
                ('background_attachment', models.CharField(choices=[('scroll', 'Rolar com a página'), ('fixed', 'Fixo (parallax)')], default='scroll', help_text='Como a imagem se comporta durante o scroll', max_length=50)),
                ('background_image', models.ForeignKey(blank=True, help_text='Imagem de fundo que será usada em todas as páginas internas do site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configurações do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
