# Generated by Django 5.2.6 on 2025-09-18 23:25

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Case')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('category', models.CharField(choices=[('ecommerce', 'E-commerce'), ('saas', 'SaaS/Software'), ('servicos', 'Serviços'), ('varejo', 'Varejo'), ('industria', 'Indústria'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('imobiliaria', 'Imobiliária'), ('automotivo', 'Automotivo'), ('outros', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('short_description', models.TextField(help_text='Descrição resumida para cards e previews', max_length=300, verbose_name='Descrição Curta')),
                ('challenge', wagtail.fields.RichTextField(help_text='Qual era o desafio do cliente?', verbose_name='Desafio')),
                ('solution', wagtail.fields.RichTextField(help_text='Como a Kaizen resolveu o problema?', verbose_name='Solução')),
                ('results', wagtail.fields.RichTextField(help_text='Quais foram os resultados alcançados?', verbose_name='Resultados')),
                ('main_metric_value', models.CharField(help_text='Ex: +300% de vendas', max_length=50, verbose_name='Métrica Principal')),
                ('main_metric_description', models.CharField(help_text='Ex: Aumento nas vendas em 6 meses', max_length=200, verbose_name='Descrição da Métrica')),
                ('content', wagtail.fields.StreamField([('metrics', 3), ('gallery', 6), ('paragraph', 7), ('heading', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Nome da Métrica', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Valor', 'max_length': 50}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Descrição', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('metric_name', 0), ('metric_value', 1), ('metric_description', 2)]], {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Legenda', 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {})}, verbose_name='Conteúdo Adicional')),
                ('meta_description', models.TextField(blank=True, help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160, verbose_name='Meta Description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Case em Destaque')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo do Cliente')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem Principal')),
            ],
            options={
                'verbose_name': 'Case de Sucesso',
                'verbose_name_plural': 'Cases de Sucesso',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('additional_content', wagtail.fields.RichTextField(blank=True, verbose_name='Conteúdo Adicional')),
                ('cta_title', models.CharField(default='Quer resultados similares?', max_length=100, verbose_name='Título do CTA')),
                ('cta_text', models.TextField(default='Entre em contato e descubra como podemos ajudar seu negócio a crescer.', verbose_name='Texto do CTA')),
                ('cta_button_text', models.CharField(default='Fale Conosco', max_length=50, verbose_name='Texto do Botão')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='Case')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CaseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Cases de Sucesso', max_length=200, verbose_name='Título Principal')),
                ('hero_subtitle', wagtail.fields.RichTextField(default='<p>Resultados reais que transformaram negócios e geraram crescimento exponencial</p>', verbose_name='Subtítulo Principal')),
                ('show_category_filters', models.BooleanField(default=True, verbose_name='Mostrar Filtros por Categoria')),
                ('show_featured_section', models.BooleanField(default=True, verbose_name='Mostrar Seção de Cases em Destaque')),
                ('meta_description', models.TextField(default='Cases de sucesso da Agência Kaizen. Veja como transformamos negócios e geramos resultados reais para nossos clientes.', max_length=160, verbose_name='Meta Description')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem do Hero')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
